# Generated by Django 3.0.5 on 2020-05-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.CharField(choices=[('Garçon', 'Garcon'), ('Fille', 'Fille')], max_length=10),
        ),
    ]
